# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IO6vmAMXQOt4W7Wt8Y57eqP2h2e6gHqle0Bo2kOlYc7m1y6q+UnngNvZowMLXt7JkQHDwkjdUZohzc6FhawEwmMEqGKw0AZz6JJW7h7TRQndaOVyo30TKIgCz/nlxD7ZK2KJScucVXsvWvoxSHJd/7FUZocjjWOiNHVQHkz16sVU0OaEp4pMdadyuZxp5ILKobnNPzu4CD+GgNgzKyLhVYGw+2HpMTWjGdCCsgns+1Y+ilGukxBtD9XeD7K0kUcTHtPs5agwiPbKCxAdeb7kQ4I5Mxx1O9DpmOpX8raUbCLfSu5Q70y/8UjFPeXIw31Ls5jXpq6t03CF6hQ2uOHHwc0wc1ujbO/05kqz/jawst0hTZHN3f/L/m1cahtC1zsfKi4KaegpRl2IznaLXKSzVltI3TFZmUkCMT2675QzK8OcggLL7yBquxWmLrbuXTPiYqZOK0af906GTySonXeXN8Jis7i6bgYR2yvuI3BRetQZdppRu9t7TMl4HV1AbJbloIBNLOTLER6CHPoZ6rShzydd2Ib7jQl/Ux1Zn7Z1vNATJzxOPaUHemLHH9Mrg8MvA1gkpNhp8P5qb7yAVwesHO9UnkMqRXuApj4nQsgAphKna55QaN6cA4OY6+xrD4Tc6oY/nktem9G5pl3aO76sud4pDHRgDQkYfnugZz/iY18="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
