appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IO6vmAMXQOt4W7Wt8Y57eqP2h2e6gHqle0Bo2kOlYc7m1y6q+UnngNvZowMLXt7JkQHDwkjdUZohzc6FhawEwmMEqGKw0AZz6JJW7h7TRQndaOVyo30TKIgCz/nlxD7ZK2KJScucVXsvWvoxSHJd/7FUZocjjWOiNHVQHkz16sVU0OaEp4pMdadyuZxp5ILKobnNPzu4CD+GgNgzKyLhVYGw+2HpMTWjGdCCsgns+1Y+ilGukxBtD9XeD7K0kUcTHtPs5agwiPbKCxAdeb7kQ4I5Mxx1O9DpmOpX8raUbCLfSu5Q70y/8UjFPeXIw31Ls5jXpq6t03CF6hQ2uOHHwc0wc1ujbO/05kqz/jawst0hTZHN3f/L/m1cahtC1zsfKi4KaegpRl2IznaLXKSzVltI3TFZmUkCMT2675QzK8OcggLL7yBquxWmLrbuXTPiYqZOK0af906GTySonXeXN8Jis7i6bgYR2yvuI3BRetQZdppRu9t7TMl4HV1AbJbloIBNLOTLER6CHPoZ6rShzydd2Ib7jQl/Ux1Zn7Z1vNATJzxOPaUHemLHH9Mrg8MvA1gkpNhp8P5qb7yAVwesHO9UnkMqRXuApj4nQsgAphKna55QaN6cA4OY6+xrD4Tc6oY/nktem9G5pl3aO76sud4pDHRgDQkYfnugZz/iY18=}
