travis:
  secure:
    BINSTAR_TOKEN: qe5NUMWiriDDVMXM7LvpdmFwLe7F2lAufM+wZKiNSDC/JlE57ZBd/kcOJT3rfyOZParC5PPbz2U2LbkjGi0XTurjErnA648lb3hFy0xxjB9q9dgAwvMbmTURhR8AqKcpY/0kT4AiGnf+3Ix/OE4K2Z0ALRDCHcbqY1w4REKRZwKDEZ5myNIWLaLSqwrA8UP2luqj5GSFpvKVSSV2/dwsqTKlrD65+JT2f3C4vs/EmIR//v4k5bMwgO1VLiVjVfu5ZxfyMVo9bWkTtkUVxejfasTIJv6JMSfEUAZVV3ZQ3RYh1zNCUNw7Nw8p3tT45Olzvx6cBjdr29qvryqnNH1srcu/sG8Wj7AnHH6ydP4futizpqEIOqzYuljFRfvwt23P/99QefdVCH3ggYvzYhUd8zMS4dL6NKi1dlwIbwtW7iZQqAf+uPt5ADjI9MDoqfurHj+ZmXysCxbjufi0UmjFYpDe6ByvhqSGRoJ9N7Y+jRNVwebL0Eaa0Zaq30j1H2MAlYbwsBs5JIUwZfq5/iXsYhygIISrKD5Dw+pt+zoYl6jin87C78bdNUtaFMbGCOPD8cTGpqiBHxyb7B+isfFMpJbL/zPiSoSsE/4Rvsn+cHa+sNl+NsAH5TIcGVpENZV4Z6o8xqiXf0/PCwEK7/AwVwvApsxpeiqRuFBgwyRE/Lo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
